---
# Build a bundle to play with enos
- hosts: all
  tasks:
  - name: Install bundle dependencies
    apt: name={{ item }} state=present update_cache=yes
    with_items:
      # Sanity
      - htop
      - jq
      - vim
      # Enos & Co
      - git
      - libffi-dev
      - libssl-dev
      - python-dev
      - python-pip
      - python-virtualenv
      - python-setuptools
      - openvswitch-switch
      # debug
      - bridge-utils
      - tcpdump
    become: true

  - name: Generate a new ssh key for kolla-ansible
    command: ssh-keygen -t rsa -P '' -f '/home/vagrant/.ssh/id_rsa'
    args:
      creates: /home/vagrant/.ssh/id_rsa

  - name: Put ssh public key into root authorized_keys to authorize root ssh connections
    shell: |
      mkdir /root/.ssh/
      cat /home/vagrant/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
    args:
      creates: /root/.ssh/autorized_keys
    become: true

  - name: Download cirros into /home/vagrant
    get_url:
      url: http://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img
      dest: /home/vagrant/cirros.qcow2

  # - name: Download debian-9 into /home/vagrant (see, https://cdimage.debian.org/cdimage/openstack/current-9/)
  #   get_url:
  #     url: https://cdimage.debian.org/cdimage/openstack/current-9/debian-9-openstack-amd64.qcow2
  #     dest: /home/vagrant/debian-9.qcow2

  # - name: Copy the Arch Linux on the system
  #   copy:
  #     src: arch.qcow2
  #     dest: /home/vagrant/arch.qcow2

  # - name: Download enos into /opt
  #   git:
  #     repo: "{{ enos.repo }}"
  #     version: "{{ enos.version }}"
  #     dest: /opt/enos
  #     depth: 1
  #     force: yes

  # - name: Copy local reservation.yaml files into /opt/enos/
  #   copy: src=reservation.yaml dest=/opt/enos

  # - name: Copy local patch directoy into /opt/enos/
  #   copy: src=patch dest=/opt/enos


  # - name: Download shaker-image into /opt/enos
  #   get_url:
  #     url: http://enos.irisa.fr/shaker-image.qcow2
  #     dest: /opt/enos/shaker-image

  # - name: Patch enos to get cirros/shaker-img from /opt rather than /tmp
  #   command: git apply patch/images-in-opt.patch
  #   args:
  #     chdir: /opt/enos

  - name: Create a directory for the virtualenv
    file: path=/home/vagrant/enos-venv state=directory

  - name: Install enos from source
    pip:
      virtualenv: /home/vagrant/enos-venv
      name: -e file:///home/vagrant/rsc/enos#egg=enos

  - name: Source venv and admin-open at user connection
    blockinfile:
      name: ~/.profile
      create: yes
      state: present
      block: |
        . /home/vagrant/enos-venv/bin/activate
        [ -f /home/vagrant/current/admin-openrc ] && . /home/vagrant/current/admin-openrc

  - name: Start of enos bootstrapping (i.e., enos deploy; enos destroy)
    debug:
      msg:
        - "Follow bootstrapping with:"
        - "vagrant ssh -- tail -f /tmp/enos-bootstrap.log"

  - name: Call enos deploy
    shell: |
      . /home/vagrant/enos-venv/bin/activate
      enos deploy -f rsc/reservation.yml 2>&1 > /tmp/enos-bootstrap.log
    args:
      chdir: /home/vagrant
      creates: /tmp/enos-deployed

  # - name: Call enos bench
  #   shell: |
  #     . venv/bin/activate
  #     python -m enos.enos bench --workload=workload 2>&1 >> /tmp/enos-bootstrap.log
  #   args:
  #     chdir: /opt/enos/
  #     creates: /tmp/enos-benched

  # - name: Clean enos
  #   shell: |
  #     . venv/bin/activate
  #     python -m enos.enos destroy 2>&1 >> /tmp/enos-bootstrap.log
  #     rm -rf enos_201* current
  #     sudo rm -rf /root/rally_home /root/shaker_home
  #   args:
  #     chdir: /opt/enos/
  #     creates: /tmp/enos-destroyed
