# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/debian-9.1"

  config.vm.hostname = "lab-vm"
  config.vm.network :private_network, ip: "192.168.142.127", auto_config: true
  config.vm.network :private_network, ip: "192.168.143.127", auto_config: true

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 6
    vb.memory = 8192
  end

  config.vm.synced_folder "./", "/home/vagrant/rsc",
    owner: "vagrant",
    group: "vagrant"

  config.vm.provision :ansible_local do |ansible|
    ansible.install_mode = "pip"
    ansible.version = "latest"
    ansible.playbook = "bundle.yml"
  end
end
