---
  ZaqarBasic.producer_consumer:
    -
      args:
        min_msg_count: 50
        max_msg_count: 200
      runner:
        type: "constant"
        times: {{times}}
        concurrency: {{concurrency}}
      sla:
        failure_rate:
          max: 0
