---
  MuranoEnvironments.list_environments:
    -
      runner:
        type: "constant"
        times: {{times}}
        concurrency: {{concurrency}}
      context:
        users:
          tenants: 2
          users_per_tenant: 2
        murano_environments:
          environments_per_tenant: 2
      sla:
        failure_rate:
          max: 0
